"""Step 7: TUI display and HTML report generation."""

import json
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text
from rich.markdown import Markdown


RECOMMENDATION_COLORS = {
    "FOR": "bold green",
    "AGAINST": "bold red",
    "ABSTAIN": "bold yellow",
}


def display_recommendations(filepath: str = "output/recommendations.json"):
    """Display voting recommendations in the terminal using rich."""
    console = Console()
    data = json.loads(Path(filepath).read_text())

    console.print()
    console.print(Panel.fit(
        "[bold cyan]AI Proxy Voting Assistant[/bold cyan]\n"
        "Personalized voting recommendations based on your investor profile",
        border_style="cyan",
    ))
    console.print()

    for company in data.get("companies", []):
        name = company["company"]
        ticker = company["ticker"]

        table = Table(
            title=f"\n{name} ({ticker})",
            title_style="bold white",
            show_header=True,
            header_style="bold",
            border_style="blue",
            expand=True,
        )
        table.add_column("#", style="dim", width=3)
        table.add_column("Proposal", ratio=3)
        table.add_column("Vote", justify="center", width=10)
        table.add_column("Reasoning", ratio=4)

        for prop in company.get("proposals", []):
            rec = prop.get("recommendation", "ABSTAIN")
            color = RECOMMENDATION_COLORS.get(rec, "white")
            vote_text = Text(rec, style=color)

            summary = prop.get("summary", prop.get("title", ""))
            if len(summary) > 120:
                summary = summary[:117] + "..."

            reasoning = prop.get("reasoning", "")
            if len(reasoning) > 200:
                reasoning = reasoning[:197] + "..."

            table.add_row(
                prop.get("id", "?"),
                summary,
                vote_text,
                reasoning,
            )

        console.print(table)

    console.print()
    console.print("[dim]Generated by AI Proxy Voting Assistant | For informational purposes only[/dim]")
    console.print()


def generate_html_report(
    filepath: str = "output/recommendations.json",
    output_path: str = "output/report.html",
):
    """Generate a simple HTML report of voting recommendations."""
    data = json.loads(Path(filepath).read_text())

    html_parts = ["""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Proxy Voting Recommendations</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background: #0d1117; color: #c9d1d9; }
  h1 { color: #58a6ff; border-bottom: 1px solid #30363d; padding-bottom: 10px; }
  h2 { color: #c9d1d9; margin-top: 30px; }
  .company { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 20px; margin: 20px 0; }
  .proposal { border-left: 3px solid #30363d; padding: 12px 16px; margin: 12px 0; background: #0d1117; border-radius: 0 6px 6px 0; }
  .proposal-title { font-weight: 600; margin-bottom: 6px; }
  .summary { color: #8b949e; font-size: 0.9em; margin: 6px 0; }
  .reasoning { color: #8b949e; font-size: 0.85em; margin-top: 8px; font-style: italic; }
  .badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-weight: 700; font-size: 0.85em; }
  .badge-FOR { background: #238636; color: #fff; }
  .badge-AGAINST { background: #da3633; color: #fff; }
  .badge-ABSTAIN { background: #9e6a03; color: #fff; }
  .footer { text-align: center; color: #484f58; margin-top: 40px; font-size: 0.85em; }
</style>
</head>
<body>
<h1>Proxy Voting Recommendations</h1>
<p>Personalized voting recommendations based on your investor profile.</p>
"""]

    for company in data.get("companies", []):
        html_parts.append(f'<div class="company">')
        html_parts.append(f'<h2>{company["company"]} ({company["ticker"]})</h2>')

        for prop in company.get("proposals", []):
            rec = prop.get("recommendation", "ABSTAIN")
            html_parts.append(f'<div class="proposal">')
            html_parts.append(f'  <div class="proposal-title">Proposal {prop.get("id", "?")}: {prop.get("title", "")}</div>')
            html_parts.append(f'  <span class="badge badge-{rec}">{rec}</span>')
            if prop.get("summary"):
                html_parts.append(f'  <div class="summary">{prop["summary"]}</div>')
            if prop.get("reasoning"):
                html_parts.append(f'  <div class="reasoning">{prop["reasoning"]}</div>')
            html_parts.append(f'</div>')

        html_parts.append('</div>')

    html_parts.append("""
<div class="footer">Generated by AI Proxy Voting Assistant | For informational purposes only</div>
</body>
</html>""")

    html = "\n".join(html_parts)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(html)
    return output_path
